apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prom-stack
    app: dotnetcoretest
  name: dotnetcoretest
  namespace: default
spec:
  endpoints:
  - interval: 15s
    port: web
    scheme: http
    #namespaceSelector:
    #  matchNames:
    #  - default
  selector:
    matchLabels:
      app: dotnetcoretest
